# This file provides instructions for packaging.

@prefix : <http://purl.org/NET/cpan-uri/terms#> .

<http://purl.org/NET/cpan-uri/dist/RT-ClientX-GrabBugs/project>
	:test_requires
		"Test::More 0.96";
	:recommends
		"RDF::TrineX::Serializer::MockTurtleSoup";
	:requires
		"perl 5.010",
		"Moose 2.0600",
		"namespace::autoclean",
		"Try::Tiny",
		"Types::Standard",
		"Getopt::ArgvFile",
		"Getopt::Long",
		"RDF::Trine 0.130",
		"RT::Client::REST",
		"RT::Client::REST::Queue",
		"Path::FindDev".
