# This file provides instructions for packaging.

@prefix : <http://ontologi.es/doap-deps#> .

<http://purl.org/NET/cpan-uri/dist/RT-ClientX-GrabBugs/project>
	:test-requirement       [ :on "Test::More 0.96"^^:CpanId ];
	:runtime-recommendation [ :on "RDF::TrineX::Serializer::MockTurtleSoup"^^:CpanId ];
	:runtime-requirement    [ :on "perl 5.010"^^:CpanId ];
	:runtime-requirement    [ :on "Moose 2.0600"^^:CpanId ];
	:runtime-requirement    [ :on "namespace::autoclean"^^:CpanId ];
	:runtime-requirement    [ :on "Try::Tiny"^^:CpanId ];
	:runtime-requirement    [ :on "Types::Standard 0.038"^^:CpanId ];
	:runtime-requirement    [ :on "Getopt::ArgvFile"^^:CpanId ];
	:runtime-requirement    [ :on "Getopt::Long"^^:CpanId ];
	:runtime-requirement    [ :on "RDF::Trine 0.130"^^:CpanId ];
	:runtime-requirement    [ :on "RT::Client::REST"^^:CpanId ];
	:runtime-requirement    [ :on "RT::Client::REST::Queue"^^:CpanId ];
	:runtime-requirement    [ :on "Path::FindDev"^^:CpanId ];
	.